/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.utils.Auth;
import com.edusys.utils.DialogHelPer;
import com.edusys.utils.XImage;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    void init() {
//        setIconImage(XImage.APP_ICON);

        setLocationRelativeTo(null);
        new Timer(1000, new ActionListener() {
            SimpleDateFormat fomat = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(fomat.format(new Date()));
            }
        }).start();
        this.openWellcome();
        this.Login();
        this.info();
    }

    public void info() {
        String rode = String.valueOf(Auth.user.isVaiTro());
        lblUser.setText(Auth.user.getHoTen());
        if (rode.equals("true")) {
            lblVaiTro.setText("Trưởng phòng");
        } else {
            lblVaiTro.setText("Nhân viên");
        }
    }

    public MainJFrame() {
        initComponents();
        change();
        init();
    }

    public void openWellcome() {
        ChaoJDialog chao = new ChaoJDialog((this), true);
        chao.setVisible(true);
    }

    public void Login() {
        DangNhap login = new DangNhap((this), true);
        login.setVisible(true);
    }
    
    public void LogOff(){
        Auth.clear();
        this.Login();
    }

    public void DoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhauJDialog(this, true).setVisible(true);
        } else {
            DialogHelPer.alert(this, "Vui lòng đăng nhập!");
        }
    }

    public void jdialogNhanVien() {
        QuanLyNhanVien nhanvien = new QuanLyNhanVien(this, true);
        nhanvien.setVisible(true);
    }

    public void QLChuyenDe() {
        QuanLyChuyenDe chuyenDe = new QuanLyChuyenDe(this, true);
        chuyenDe.setVisible(true);
    }

    public void QLKhoaHoc() {
        QuanLyKhoahoc khoaHoc = new QuanLyKhoahoc(this, true);
        khoaHoc.setVisible(true);
    }

    public void QLHocVien() {
        QuanLyHocVien hocVien = new QuanLyHocVien(this, true);
        hocVien.setVisible(true);
    }

    public void TongHop_DoanhThu(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                DialogHelPer.alert(this, "Chỉ trưởng phòng mới được phép xem thông tin doanh thu.");
                return;
            }
            QuanLyThongKe qltk = new QuanLyThongKe(this, true);
            qltk.selectTabs(index);
            qltk.setVisible(true);
        } else {
            DialogHelPer.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        btnDawngXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        btnKhoahoc = new javax.swing.JButton();
        btnNguoihoc = new javax.swing.JButton();
        btnChueynde = new javax.swing.JButton();
        btnHuongdan = new javax.swing.JButton();
        btnTOngHopDoanhThu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        pnlTrangThai = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDawnhnhap = new javax.swing.JMenuItem();
        mniDangxuat = new javax.swing.JMenuItem();
        mniDoimatkhau = new javax.swing.JMenuItem();
        mniKetthuc = new javax.swing.JMenuItem();
        mnuQuanly = new javax.swing.JMenu();
        mniNguoihoc = new javax.swing.JMenuItem();
        mniNhanvien = new javax.swing.JMenuItem();
        mniKhoahoc = new javax.swing.JMenuItem();
        mnichuyende = new javax.swing.JMenuItem();
        mnichuyende1 = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniTKnguoihoc = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniTKbangdiemkhoa = new javax.swing.JMenuItem();
        mniTKdiemtungkhoa = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniTKdoanhthutungchuende = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mnihuongdansudung = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniGioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");

        toolBar.setRollover(true);
        toolBar.setPreferredSize(new java.awt.Dimension(100, 50));

        btnDawngXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Exit.png"))); // NOI18N
        btnDawngXuat.setText("Đăng xuất");
        btnDawngXuat.setFocusable(false);
        btnDawngXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDawngXuat.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnDawngXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDawngXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDawngXuatActionPerformed(evt);
            }
        });
        toolBar.add(btnDawngXuat);

        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Stop.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        toolBar.add(btnKetThuc);

        btnKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Certificate.png"))); // NOI18N
        btnKhoahoc.setText("Khóa học");
        btnKhoahoc.setFocusable(false);
        btnKhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoahoc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnKhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoahocActionPerformed(evt);
            }
        });
        toolBar.add(btnKhoahoc);

        btnNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Conference.png"))); // NOI18N
        btnNguoihoc.setText("Người học");
        btnNguoihoc.setFocusable(false);
        btnNguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoihoc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnNguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoihocActionPerformed(evt);
            }
        });
        toolBar.add(btnNguoihoc);

        btnChueynde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/List.png"))); // NOI18N
        btnChueynde.setText("Chyên đề");
        btnChueynde.setFocusable(false);
        btnChueynde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChueynde.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnChueynde.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChueynde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChueyndeActionPerformed(evt);
            }
        });
        toolBar.add(btnChueynde);

        btnHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Globe.png"))); // NOI18N
        btnHuongdan.setText("Hướng dẫn");
        btnHuongdan.setFocusable(false);
        btnHuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongdan.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnHuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongdanActionPerformed(evt);
            }
        });
        toolBar.add(btnHuongdan);

        btnTOngHopDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Price list.png"))); // NOI18N
        btnTOngHopDoanhThu.setText("TH & DT");
        btnTOngHopDoanhThu.setFocusable(false);
        btnTOngHopDoanhThu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTOngHopDoanhThu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTOngHopDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTOngHopDoanhThuActionPerformed(evt);
            }
        });
        toolBar.add(btnTOngHopDoanhThu);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("User: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Role:");

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 51, 51));

        lblVaiTro.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblVaiTro.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        toolBar.add(jPanel1);

        getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);

        pnlTrangThai.setPreferredSize(new java.awt.Dimension(517, 25));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Info.png"))); // NOI18N
        jLabel2.setText("Hệ quản lý đào tạo");

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Alarm.png"))); // NOI18N
        lblDongHo.setText("09:27:12 AM");

        javax.swing.GroupLayout pnlTrangThaiLayout = new javax.swing.GroupLayout(pnlTrangThai);
        pnlTrangThai.setLayout(pnlTrangThaiLayout);
        pnlTrangThaiLayout.setHorizontalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangThaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 571, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addContainerGap())
        );
        pnlTrangThaiLayout.setVerticalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangThaiLayout.createSequentialGroup()
                .addGroup(pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDongHo))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTrangThai, java.awt.BorderLayout.PAGE_END);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/LogoBig.png"))); // NOI18N
        getContentPane().add(jLabel4, java.awt.BorderLayout.CENTER);

        mnuHeThong.setText("Hệ thống");

        mniDawnhnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mniDawnhnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Key.png"))); // NOI18N
        mniDawnhnhap.setText("Đăng nhập");
        mnuHeThong.add(mniDawnhnhap);

        mniDangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Log out.png"))); // NOI18N
        mniDangxuat.setText("Đăng xuất");
        mniDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangxuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangxuat);

        mniDoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Refresh.png"))); // NOI18N
        mniDoimatkhau.setText("Đổi mật khẩu");
        mniDoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoimatkhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoimatkhau);

        mniKetthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Stop.png"))); // NOI18N
        mniKetthuc.setText("Kết thúc");
        mnuHeThong.add(mniKetthuc);

        jMenuBar1.add(mnuHeThong);

        mnuQuanly.setText("Quản lý");

        mniNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Conference.png"))); // NOI18N
        mniNguoihoc.setText("Người học");
        mniNguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoihocActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniNguoihoc);

        mniNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Lists.png"))); // NOI18N
        mniNhanvien.setText("Nhân viên");
        mniNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanvienActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniNhanvien);

        mniKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Certificate.png"))); // NOI18N
        mniKhoahoc.setText("Khóa học");
        mniKhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoahocActionPerformed(evt);
            }
        });
        mnuQuanly.add(mniKhoahoc);

        mnichuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/User group.png"))); // NOI18N
        mnichuyende.setText("Chuyên đề");
        mnichuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnichuyendeActionPerformed(evt);
            }
        });
        mnuQuanly.add(mnichuyende);

        mnichuyende1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/User group.png"))); // NOI18N
        mnichuyende1.setText("Hoc vien");
        mnichuyende1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnichuyende1ActionPerformed(evt);
            }
        });
        mnuQuanly.add(mnichuyende1);

        jMenuBar1.add(mnuQuanly);

        mnuThongKe.setText("Thống kê");

        mniTKnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Clien list.png"))); // NOI18N
        mniTKnguoihoc.setText("Người học tùng năm");
        mniTKnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKnguoihocActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKnguoihoc);
        mnuThongKe.add(jSeparator1);

        mniTKbangdiemkhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Card file.png"))); // NOI18N
        mniTKbangdiemkhoa.setText("Bảng điểm khóa...");
        mniTKbangdiemkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKbangdiemkhoaActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKbangdiemkhoa);

        mniTKdiemtungkhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Bar chart.png"))); // NOI18N
        mniTKdiemtungkhoa.setText("Điểm từng khóa");
        mniTKdiemtungkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKdiemtungkhoaActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKdiemtungkhoa);
        mnuThongKe.add(jSeparator2);

        mniTKdoanhthutungchuende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Dollar.png"))); // NOI18N
        mniTKdoanhthutungchuende.setText("Doanh thu từng chuyên đề...");
        mniTKdoanhthutungchuende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKdoanhthutungchuendeActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKdoanhthutungchuende);

        jMenuBar1.add(mnuThongKe);

        mnuTroGiup.setText("Trợ giúp");

        mnihuongdansudung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnihuongdansudung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Globe.png"))); // NOI18N
        mnihuongdansudung.setText("Hướng dẫn sử dụng");
        mnihuongdansudung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihuongdansudungActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mnihuongdansudung);
        mnuTroGiup.add(jSeparator3);

        mniGioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.edusys.icon/Brick house.png"))); // NOI18N
        mniGioithieu.setText("Giới thiệu sản phẩm");
        mniGioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioithieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioithieu);

        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangxuatActionPerformed
        // TODO add your handling code here:
        LogOff();
    }//GEN-LAST:event_mniDangxuatActionPerformed

    private void mniDoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoimatkhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhau();
    }//GEN-LAST:event_mniDoimatkhauActionPerformed

    private void mniNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanvienActionPerformed
        // TODO add your handling code here:
        jdialogNhanVien();
    }//GEN-LAST:event_mniNhanvienActionPerformed

    private void mnichuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnichuyendeActionPerformed
        // TODO add your handling code here:
        QLChuyenDe();
    }//GEN-LAST:event_mnichuyendeActionPerformed

    private void mniTKbangdiemkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKbangdiemkhoaActionPerformed
        // TODO add your handling code here:
        TongHop_DoanhThu(1);
    }//GEN-LAST:event_mniTKbangdiemkhoaActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
        if (DialogHelPer.confirm(this, "Bạn muốn kết thuc ứng dụng")) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void mniKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoahocActionPerformed
        // TODO add your handling code here:
        QLKhoaHoc();
    }//GEN-LAST:event_mniKhoahocActionPerformed

    private void btnKhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoahocActionPerformed
        // TODO add your handling code here:
        QLKhoaHoc();
    }//GEN-LAST:event_btnKhoahocActionPerformed

    private void mnichuyende1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnichuyende1ActionPerformed
        // TODO add your handling code here:
        this.QLHocVien();
    }//GEN-LAST:event_mnichuyende1ActionPerformed

    private void btnHuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongdanActionPerformed
        // TODO add your handling code here:
        try {

            Desktop.getDesktop().browse(new File("help/HuongDan.html").toURI());
        } catch (Exception e) {
            DialogHelPer.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }//GEN-LAST:event_btnHuongdanActionPerformed

    private void btnTOngHopDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTOngHopDoanhThuActionPerformed
        // TODO add your handling code here:
        TongHop_DoanhThu(0);
    }//GEN-LAST:event_btnTOngHopDoanhThuActionPerformed

    private void btnDawngXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDawngXuatActionPerformed
        // TODO add your handling code here:
        LogOff();
    }//GEN-LAST:event_btnDawngXuatActionPerformed

    private void mniTKnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKnguoihocActionPerformed
        // TODO add your handling code here:
        TongHop_DoanhThu(0);
    }//GEN-LAST:event_mniTKnguoihocActionPerformed

    private void mniTKdiemtungkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKdiemtungkhoaActionPerformed
        // TODO add your handling code here:
        TongHop_DoanhThu(2);
    }//GEN-LAST:event_mniTKdiemtungkhoaActionPerformed

    private void mniTKdoanhthutungchuendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKdoanhthutungchuendeActionPerformed
        // TODO add your handling code here:
        TongHop_DoanhThu(3);
    }//GEN-LAST:event_mniTKdoanhthutungchuendeActionPerformed

    private void btnNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoihocActionPerformed
        // TODO add your handling code here:
        QuanLyNguoiHoc QlNguoiHoc = new QuanLyNguoiHoc(this, true);
        QlNguoiHoc.setVisible(true);
    }//GEN-LAST:event_btnNguoihocActionPerformed

    private void mniNguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoihocActionPerformed
        // TODO add your handling code here:
        QuanLyNguoiHoc QlNguoiHoc = new QuanLyNguoiHoc(this, true);
        QlNguoiHoc.setVisible(true);
    }//GEN-LAST:event_mniNguoihocActionPerformed

    private void mnihuongdansudungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihuongdansudungActionPerformed
        // TODO add your handling code here:
        try {

            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (Exception e) {
            DialogHelPer.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }//GEN-LAST:event_mnihuongdansudungActionPerformed

    private void btnChueyndeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChueyndeActionPerformed
        // TODO add your handling code here:
        QLChuyenDe();
    }//GEN-LAST:event_btnChueyndeActionPerformed

    private void mniGioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioithieuActionPerformed
        // TODO add your handling code here:
        GioithieuJDialog gioiThieu = new GioithieuJDialog(this, true);
        gioiThieu.setVisible(true);
    }//GEN-LAST:event_mniGioithieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public void change() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("fpt_icon.png")));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChueynde;
    private javax.swing.JButton btnDawngXuat;
    private javax.swing.JButton btnHuongdan;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhoahoc;
    private javax.swing.JButton btnNguoihoc;
    private javax.swing.JButton btnTOngHopDoanhThu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JMenuItem mniDangxuat;
    private javax.swing.JMenuItem mniDawnhnhap;
    private javax.swing.JMenuItem mniDoimatkhau;
    private javax.swing.JMenuItem mniGioithieu;
    private javax.swing.JMenuItem mniKetthuc;
    private javax.swing.JMenuItem mniKhoahoc;
    private javax.swing.JMenuItem mniNguoihoc;
    private javax.swing.JMenuItem mniNhanvien;
    private javax.swing.JMenuItem mniTKbangdiemkhoa;
    private javax.swing.JMenuItem mniTKdiemtungkhoa;
    private javax.swing.JMenuItem mniTKdoanhthutungchuende;
    private javax.swing.JMenuItem mniTKnguoihoc;
    private javax.swing.JMenuItem mnichuyende;
    private javax.swing.JMenuItem mnichuyende1;
    private javax.swing.JMenuItem mnihuongdansudung;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanly;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPanel pnlTrangThai;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
